In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
## Define the vocabulary size
voc_size=10000

In [17]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4176, 546, 3945, 7457],
 [4176, 546, 3945, 4925],
 [4176, 6237, 3945, 2525],
 [2068, 1963, 8437, 7119, 2067],
 [2068, 1963, 8437, 7119, 5249],
 [9057, 4176, 8619, 3945, 1297],
 [9271, 3154, 9628, 7119]]

In [18]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding ,Flatten, Dense
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4176  546 3945 7457]
 [   0    0    0    0 4176  546 3945 4925]
 [   0    0    0    0 4176 6237 3945 2525]
 [   0    0    0 2068 1963 8437 7119 2067]
 [   0    0    0 2068 1963 8437 7119 5249]
 [   0    0    0 9057 4176 8619 3945 1297]
 [   0    0    0    0 9271 3154 9628 7119]]


In [21]:
## feature representation
dim=10

In [22]:
# Build the model correctly
model = Sequential([
    Embedding(input_dim=voc_size, output_dim=dim),  # Removed `input_length`
    Flatten(),  # Flatten embedding output for dense layers
    Dense(1, activation="sigmoid")  # Example output layer
])

# Compile the model
model.compile(optimizer="adam", loss="mse")


In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[0.496112  ],
       [0.49448618],
       [0.49640372],
       [0.49122506],
       [0.48607117],
       [0.49942717],
       [0.49160737]], dtype=float32)